const SUPABASE_URL='https://jsozyudrzmijdtmulzjy.supabase.co';
const SUPABASE_KEY='sb_publishable_LA4awTh-pvj1fvwXixP8Og_v6KYKai2';
const cloud=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const KEY='daybook-v1';
const today=()=>new Date().toISOString().slice(0,10);
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{tasks:[],chores:[{id:crypto.randomUUID(),name:'Take out garbage',days:7,nextDue:today()}],habits:[{id:crypto.randomUUID(),name:'Cleaning room',minutes:15,lastCompleted:null,streak:0}]};
state.tasks=state.tasks||[];state.chores=state.chores||[];state.habits=state.habits||[{id:crypto.randomUUID(),name:'Cleaning room',minutes:15,lastCompleted:null,streak:0}];
let cloudUser=null,cloudReady=false,saveTimer;let calendarDate=new Date();
state.habits.forEach(h=>{h.completionDates=h.completionDates||[...(h.lastCompleted?[h.lastCompleted]:[])]});
const esc=s=>{const d=document.createElement('div');d.textContent=s;return d.innerHTML};
const fmt=d=>!d?'No due date':d===today()?'Due today':new Date(d+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'});
function render(){const tasks=document.querySelector('#task-list');tasks.innerHTML=state.tasks.length?state.tasks.map(t=>`<div class="item ${t.done?'done':''}"><button class="check" data-task="${t.id}" aria-label="Complete"></button><div><div class="name">${esc(t.name)}</div><div class="meta">${fmt(t.due)}</div></div><button class="delete" data-del-task="${t.id}" aria-label="Delete">×</button></div>`).join(''):'<p class="empty">Nothing on your list. Add one thing above.</p>';document.querySelector('#task-count').textContent=`${state.tasks.filter(t=>!t.done).length} open`;const chores=document.querySelector('#chore-list');chores.innerHTML=state.chores.length?state.chores.map(c=>`<div class="item"><button class="check" data-chore="${c.id}" aria-label="Mark chore done"></button><div><div class="name">${esc(c.name)}</div><div class="meta">${fmt(c.nextDue)} · every ${c.days===1?'day':c.days+' days'}</div></div><button class="delete" data-del-chore="${c.id}" aria-label="Delete">×</button></div>`).join(''):'<p class="empty">Add chores that repeat automatically.</p>';const habits=document.querySelector('#habit-list');habits.innerHTML=state.habits.map(h=>`<article class="habit-card ${h.lastCompleted===today()?'habit-done':''}"><div><strong>${esc(h.name)}</strong><p>${h.minutes} minutes · ${h.streak||0} day streak</p></div><button data-habit="${h.id}" ${h.lastCompleted===today()?'disabled':''}>${h.lastCompleted===today()?'Done today':'Mark done'}</button><button class="delete" data-del-habit="${h.id}" aria-label="Delete habit">×</button></article>`).join('');renderCalendar()}
function renderCalendar(){const now=new Date(),y=now.getFullYear(),m=now.getMonth(),days=new Date(y,m+1,0).getDate();let rows='',total=0;for(const h of state.habits){const done=new Set(h.completionDates||[]);let cells='';for(let d=1;d<=31;d++){const key=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,valid=d<=days,hit=valid&&done.has(key);if(hit)total++;cells+=`<span class="tracker-cell ${hit?'followed':''} ${key===today()?'today':''} ${valid?'':'disabled'}">${hit?'✓':''}</span>`}rows+=`<div class="tracker-row"><strong>${esc(h.name)}</strong>${cells}</div>`}document.querySelector('#habit-calendar').innerHTML=rows;document.querySelector('#calendar-summary').textContent=`${now.toLocaleDateString(undefined,{month:'long',year:'numeric'})} · ${total} completed check-in${total===1?'':'s'}`}
async function pushCloud(){if(!cloudUser||!cloudReady)return;document.querySelector('#sync-status').textContent='Syncing…';const{error}=await cloud.from('daybook_data').upsert({user_id:cloudUser.id,data:state,updated_at:new Date().toISOString()});document.querySelector('#sync-status').textContent=error?'Sync error — try again':'Synced'}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();clearTimeout(saveTimer);saveTimer=setTimeout(pushCloud,250)}
function addTask(name,due){state.tasks.unshift({id:crypto.randomUUID(),name,due,done:false});save()}
function completeChore(id){const c=state.chores.find(x=>x.id===id),d=new Date();d.setDate(d.getDate()+Number(c.days));c.nextDue=d.toISOString().slice(0,10);save()}
function completeHabit(id){const h=state.habits.find(x=>x.id===id);if(h.lastCompleted===today())return;const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);h.streak=h.lastCompleted===yesterday.toISOString().slice(0,10)?(h.streak||0)+1:1;h.lastCompleted=today();h.completionDates=h.completionDates||[];if(!h.completionDates.includes(today()))h.completionDates.push(today());save()}
async function loadCloud(user){cloudUser=user;document.querySelector('#auth-form').hidden=true;document.querySelector('#sign-out').hidden=false;document.querySelector('#sync-status').textContent='Loading cloud data…';const{data,error}=await cloud.from('daybook_data').select('data').eq('user_id',user.id).maybeSingle();if(error){document.querySelector('#sync-status').textContent='Sync error';return}if(data?.data){state=data.data;state.tasks=state.tasks||[];state.chores=state.chores||[];state.habits=state.habits||[{id:crypto.randomUUID(),name:'Cleaning room',minutes:15,lastCompleted:null,streak:0}];state.habits.forEach(h=>{h.completionDates=h.completionDates||[...(h.lastCompleted?[h.lastCompleted]:[])]});localStorage.setItem(KEY,JSON.stringify(state));render()}cloudReady=true;if(!data)await pushCloud();else document.querySelector('#sync-status').textContent='Synced'}
async function initAuth(){const{data}=await cloud.auth.getSession();if(data.session)await loadCloud(data.session.user);cloud.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_IN'&&session&&!cloudUser)loadCloud(session.user)})}
document.querySelector('#quick-add').onsubmit=e=>{e.preventDefault();addTask(document.querySelector('#task-input').value.trim(),document.querySelector('#task-date').value);e.target.reset()};
document.body.onclick=e=>{const x=e.target.dataset;if(x.task){const t=state.tasks.find(t=>t.id===x.task);t.done=!t.done;save()}if(x.chore)completeChore(x.chore);if(x.habit)completeHabit(x.habit);if(x.delHabit){state.habits=state.habits.filter(h=>h.id!==x.delHabit);save()}if(x.delTask){state.tasks=state.tasks.filter(t=>t.id!==x.delTask);save()}if(x.delChore){state.chores=state.chores.filter(c=>c.id!==x.delChore);save()}};
const dlg=document.querySelector('#chore-dialog');document.querySelector('#habit-form').onsubmit=e=>{e.preventDefault();state.habits.push({id:crypto.randomUUID(),name:document.querySelector('#habit-name').value.trim(),minutes:+document.querySelector('#habit-minutes').value,lastCompleted:null,streak:0});e.target.reset();document.querySelector('#habit-minutes').value=15;save()};document.querySelector('#add-chore').onclick=()=>dlg.showModal();document.querySelector('#chore-form').onsubmit=e=>{if(e.submitter.value==='cancel')return;state.chores.push({id:crypto.randomUUID(),name:document.querySelector('#chore-name').value.trim(),days:+document.querySelector('#chore-frequency').value,nextDue:today()});e.target.reset();save()};
document.querySelector('#auth-form').onsubmit=async e=>{e.preventDefault();const status=document.querySelector('#sync-status'),button=e.submitter;button.disabled=true;status.textContent='Sending sign-in email…';try{const{error}=await cloud.auth.signInWithOtp({email:document.querySelector('#email').value.trim(),options:{emailRedirectTo:location.origin+location.pathname}});status.textContent=error?error.message:'Check your email for the sign-in link'}catch(error){status.textContent='Could not send email — try again'}finally{button.disabled=false}};
document.querySelector('#sign-out').onclick=async()=>{await cloud.auth.signOut();location.reload()};document.querySelector('#date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.querySelector('#install').hidden=false});document.querySelector('#install').onclick=()=>installPrompt?.prompt();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();initAuth();
